### ISSUE TITLE
collect static fails due to missing _client_pre_compiler

### ISSUE THREAD

**Issue by SmithChart** [lona-web-org/lona#273]
In lona master (87d02673e182b0405d7bab93415fd2eee5b885d3) (1.10.4 + some version bumps) and probably earlier `collect static` is broken.

After applying #272 it will fail since `_client_pre_compiler` has been removed from the LonaServer:

```
$ lona collect-static /tmp/test -s settings.py deployment_settings.py --clean
cp  [copying some stuff here... ]
Traceback (most recent call last):
  File "/home/chris/work/Projects/intern/lag-intranet/lag_intranet/../env/bin/lona", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/chris/work/Projects/github/lona/bin/lona", line 8, in <module>
    handle_command_line(sys.argv)
  File "/home/chris/work/Projects/github/lona/lona/command_line/handle_command_line.py", line 248, in handle_command_line
    collect_static(args)
  File "/home/chris/work/Projects/github/lona/lona/command_line/collect_static.py", line 102, in collect_static
    for source_file in server._client_pre_compiler.get_source_files():
AttributeError: 'LonaServer' object has no attribute '_client_pre_compiler'
```
I assume this was introduced with 7d8b5513b72d7efd48625db02ac4f5f81b311fe5.

**Comment by fscherf** [comment]
All issues related to this issue were resolved in #272. @SmithChart: Thanks for reporting and helping to resolve this issue :)
